param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "H:\IAR Systems\8.30\common\bin\cspybat" -f "D:\YSF4_FOC-016. FOC_v5.2.0_PMSM_HALL_精简\YSF4_FOC-014. FOC_v5.2.0_42PMSM_HALLSensor\EWARM\settings\YSF4_FOC-014. FOC_v5.2.YSF4_FOC-014._FOC_v5.2.0_42PMSM_HALLSensor.general.xcl" --backend -f "D:\YSF4_FOC-016. FOC_v5.2.0_PMSM_HALL_精简\YSF4_FOC-014. FOC_v5.2.0_42PMSM_HALLSensor\EWARM\settings\YSF4_FOC-014. FOC_v5.2.YSF4_FOC-014._FOC_v5.2.0_42PMSM_HALLSensor.driver.xcl" 
}
else
{
& "H:\IAR Systems\8.30\common\bin\cspybat" -f "D:\YSF4_FOC-016. FOC_v5.2.0_PMSM_HALL_精简\YSF4_FOC-014. FOC_v5.2.0_42PMSM_HALLSensor\EWARM\settings\YSF4_FOC-014. FOC_v5.2.YSF4_FOC-014._FOC_v5.2.0_42PMSM_HALLSensor.general.xcl" --debug_file=$debugfile --backend -f "D:\YSF4_FOC-016. FOC_v5.2.0_PMSM_HALL_精简\YSF4_FOC-014. FOC_v5.2.0_42PMSM_HALLSensor\EWARM\settings\YSF4_FOC-014. FOC_v5.2.YSF4_FOC-014._FOC_v5.2.0_42PMSM_HALLSensor.driver.xcl" 
}
