param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.1\common\bin\cspybat" -f "E:\Desktop\Program Project\F4-电机控制\F4-FOC矢量控制v5.2.0\YSF4_FOC-011. FOC_v5.2.0_57BLDC_HALLSensor\YSF4_FOC-011. FOC_v5.2.0_57BLDC_HALLSensor\EWARM\settings\YSF4_FOC-011. FOC_v5.2.YSF4_FOC-011._FOC_v5.2.0_57BLDC_HALLSensor.general.xcl" --backend -f "E:\Desktop\Program Project\F4-电机控制\F4-FOC矢量控制v5.2.0\YSF4_FOC-011. FOC_v5.2.0_57BLDC_HALLSensor\YSF4_FOC-011. FOC_v5.2.0_57BLDC_HALLSensor\EWARM\settings\YSF4_FOC-011. FOC_v5.2.YSF4_FOC-011._FOC_v5.2.0_57BLDC_HALLSensor.driver.xcl" 
}
else
{
& "C:\Program Files (x86)\IAR Systems\Embedded Workbench 8.1\common\bin\cspybat" -f "E:\Desktop\Program Project\F4-电机控制\F4-FOC矢量控制v5.2.0\YSF4_FOC-011. FOC_v5.2.0_57BLDC_HALLSensor\YSF4_FOC-011. FOC_v5.2.0_57BLDC_HALLSensor\EWARM\settings\YSF4_FOC-011. FOC_v5.2.YSF4_FOC-011._FOC_v5.2.0_57BLDC_HALLSensor.general.xcl" --debug_file=$debugfile --backend -f "E:\Desktop\Program Project\F4-电机控制\F4-FOC矢量控制v5.2.0\YSF4_FOC-011. FOC_v5.2.0_57BLDC_HALLSensor\YSF4_FOC-011. FOC_v5.2.0_57BLDC_HALLSensor\EWARM\settings\YSF4_FOC-011. FOC_v5.2.YSF4_FOC-011._FOC_v5.2.0_57BLDC_HALLSensor.driver.xcl" 
}
